services:
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    environment:
      - TZ=Etc/GMT+5
    ports:
      - '3000:80'
    depends_on:
      - user-service
      - doc-manager
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    env_file:
      - ./services/user-service/.env
  doc-manager:
    build:
      context: ./services/doc-manager
      dockerfile: Dockerfile
    ports:
      - '4002:4002'
    env_file:
      - ./services/doc-manager/.env
  forms-manager:
    build:
      context: ./services/forms-manager
      dockerfile: Dockerfile
    ports:
      - '4003:4003'
    env_file:
      - ./services/forms-manager/.env
